/**
 * Auto-generated Supabase database types.
 *
 * Regenerate after schema changes:
 *   pnpm supabase:types
 *
 * DO NOT edit this file manually.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string | null
          avatar_url: string | null
          facebook_id: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          created_at: string
        }
        Insert: {
          id: string
          display_name?: string | null
          avatar_url?: string | null
          facebook_id?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          display_name?: string | null
          avatar_url?: string | null
          facebook_id?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          created_at?: string
        }
        Relationships: []
      }
      listings: {
        Row: {
          id: string
          seller_id: string
          moving_sale_id: string | null
          title: string
          description: string | null
          price: number
          condition: 'new' | 'like_new' | 'good' | 'fair'
          category: string
          status: 'active' | 'reserved' | 'sold'
          city: string | null
          state: string | null
          zip_code: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          seller_id: string
          moving_sale_id?: string | null
          title: string
          description?: string | null
          price: number
          condition?: 'new' | 'like_new' | 'good' | 'fair'
          category: string
          status?: 'active' | 'reserved' | 'sold'
          city?: string | null
          state?: string | null
          zip_code?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          seller_id?: string
          moving_sale_id?: string | null
          title?: string
          description?: string | null
          price?: number
          condition?: 'new' | 'like_new' | 'good' | 'fair'
          category?: string
          status?: 'active' | 'reserved' | 'sold'
          city?: string | null
          state?: string | null
          zip_code?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      listing_photos: {
        Row: {
          id: string
          listing_id: string
          storage_path: string
          display_order: number
        }
        Insert: {
          id?: string
          listing_id: string
          storage_path: string
          display_order?: number
        }
        Update: {
          id?: string
          listing_id?: string
          storage_path?: string
          display_order?: number
        }
        Relationships: []
      }
      moving_sales: {
        Row: {
          id: string
          seller_id: string
          title: string
          description: string | null
          move_date: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          created_at: string
        }
        Insert: {
          id?: string
          seller_id: string
          title: string
          description?: string | null
          move_date?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          seller_id?: string
          title?: string
          description?: string | null
          move_date?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          created_at?: string
        }
        Relationships: []
      }
      conversations: {
        Row: {
          id: string
          listing_id: string
          buyer_id: string
          seller_id: string
          created_at: string
        }
        Insert: {
          id?: string
          listing_id: string
          buyer_id: string
          seller_id: string
          created_at?: string
        }
        Update: {
          id?: string
          listing_id?: string
          buyer_id?: string
          seller_id?: string
          created_at?: string
        }
        Relationships: []
      }
      messages: {
        Row: {
          id: string
          conversation_id: string
          sender_id: string
          content: string
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          conversation_id: string
          sender_id: string
          content: string
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          conversation_id?: string
          sender_id?: string
          content?: string
          is_read?: boolean
          created_at?: string
        }
        Relationships: []
      }
      saved_listings: {
        Row: {
          user_id: string
          listing_id: string
          saved_at: string
        }
        Insert: {
          user_id: string
          listing_id: string
          saved_at?: string
        }
        Update: {
          user_id?: string
          listing_id?: string
          saved_at?: string
        }
        Relationships: []
      }
    }
  }
}

// Convenience type aliases
export type Profile = Database['public']['Tables']['profiles']['Row']
export type Listing = Database['public']['Tables']['listings']['Row']
export type ListingPhoto = Database['public']['Tables']['listing_photos']['Row']
export type MovingSale = Database['public']['Tables']['moving_sales']['Row']
export type Conversation = Database['public']['Tables']['conversations']['Row']
export type Message = Database['public']['Tables']['messages']['Row']
export type SavedListing = Database['public']['Tables']['saved_listings']['Row']

export type ListingCondition = Listing['condition']
export type ListingStatus = Listing['status']
